id = "depender"
name = "Depender"
version = "0.0.1"
schema_version = 1
authors = ["Francisco Casiano <contact@franciscocasiano.com>"]
description = "Preview the dependencies and their versions of the corresponding language you're using without leaving Zed."
repository = "https://github.com/panchi64/depender"

[grammars.toml]
repository = "https://github.com/ikatyang/tree-sitter-toml"
commit = "8bd2056818b21860e3d756b5a58c4f6e05fb744e"

[grammars.json]
repository = "https://github.com/tree-sitter/tree-sitter-json"
commit = "94f5c527b2965465956c2000ed6134dd24daf2a7"

# TODO: Add support for:
# Python - .txt & .toml
# Ruby - (none?)
# Java - .xml & .gradle & .kts
# PHP - .json
# Go - .mod & .sum
# C#/.NET - .csproj & .config
# Elixir - .exs
# Haskell - .cabal & .yaml
# Perl - (none?)
# R - (none?) & .lock
# Swift - .swift
# Dart - .yaml
